name = "ws"
license = "MIT"
licenselink = "https://github.com/wildskyf/hugo-theme-ws/blob/master/LICENSE.md"
description = "theme for hugo"
homepage = "https://github.com/wildskyf/hugo-theme-ws"
tags = ["blog"]
features = ["blog"]
min_version = 0.30

[author]
  name = "wildsky"
  homepage = "https://github.com/wildskyf"
